apiVersion: v1
kind: Service
metadata:
  labels:
    app: medical-noshow-api
  name: medical-noshow-api
spec:
  ports:
  - name: 8000-8000
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: medical-noshow-api
  type: LoadBalancer
status:
  loadBalancer: {}
